---
title: "Histoire"
format: html
editor: visual
---

Lisez l'histoire dans l'ordre suivant :

1.  La carte au trésor

2.  L'arbre à tisane

3.  Le buisson de framboises

4.  L'ogre affamé

5.  L'ours insomniaque

6.  Le coffre au trésor

Bonne lecture.

# 4. L'ours insomniaque
Je sors de ma poche un petit flacon de miel, que je donne à l'ours insomniaque. "Merci infiniment ! C'est exactement ce dont j'avais besoin pour arriver à boire ma tisane à la camomille, sans miel c'est vraiment infect..." Me dit l'ours souriant.

# 6. Le coffre au trésor 
Dans le coffre nous croyons retrouver des objets assez surprenants. 
Nous avons vu jaillir une lumière qui nous a aveuglé. 
Malgré cet handicap visuel nous avons le coeur en fête. 
On se frotta les yeux pour mieux voir mais aussi pour revenir à la réalité .
 mais la réalité nous a percuté encore plus fort car la lumière n'était qu'un vieux phare qui s'allume dans l'obscurité. 
une fois le coffre sortie de la grotte ce phare ne servi plus à rien .
[](image/baggit_magette_coffre.jpg)

